# .github/workflows/test.yml
name: Autograder

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest

      - name: Use token
        run: git clone https://x-access-token:${{ secrets.HIDDEN_TOKEN }}@github.com/TDA-Podberezski/2025-2c-tp1-1-tests.git .
        
      - name: Run tests sts
        run: |
          pytest test.py --maxfail=1 --disable-warnings -q

      - name: Run hidden tests
        run: |
          pytest test_hidden.py --maxfail=1 --disable-warnings -q
